import { SharedRoute, UserProfile } from './types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'driver-1',
    email: 'ramesh.driver@nextride.in',
    full_name: 'Ramesh Patel',
    phone: '+91 98765 43210',
    role: 'driver',
    village_town: 'Rampur Village',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_trips: 342,
  },
  {
    id: 'driver-2',
    email: 'sukhdev.singh@nextride.in',
    full_name: 'Sukhdev Singh',
    phone: '+91 98234 11223',
    role: 'driver',
    village_town: 'Fatehgarh Rural Hub',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    total_trips: 189,
  },
  {
    id: 'traveller-1',
    email: 'anita.sharma@gmail.com',
    full_name: 'Anita Sharma',
    phone: '+91 97112 33445',
    role: 'traveller',
    village_town: 'Bhopalpur Sector 4',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    rating: 5.0,
    total_trips: 28,
  }
];

export const INITIAL_ROUTES: SharedRoute[] = [
  {
    id: 'route-101',
    driver_id: 'driver-1',
    driver_name: 'Ramesh Patel',
    driver_phone: '+91 98765 43210',
    driver_rating: 4.9,
    vehicle_type: 'Jeep / Cruiser',
    vehicle_model: 'Mahindra Bolero Maxi Truck / 9-Seater',
    plate_number: 'MP-04-AB-4921',
    origin: 'Rampur Village Chowk',
    destination: 'District Main Mandi & Hospital',
    intermediate_stops: ['Kisan Krishi Mandi', 'Old Toll Naka', 'Government Hospital Chowk', 'Tehsil Office'],
    departure_time: '07:30 AM',
    frequency: 'Daily (Morning 7:30 AM & Return 5:30 PM)',
    price_per_seat: 40,
    available_seats: 5,
    total_seats: 8,
    luggage_space: 'Heavy rooftop luggage carrier + Farm sacks allowed',
    has_carrier: true,
    is_ac: false,
    status: 'active',
    notes: 'Leaves sharp from Rampur Banyan Tree. Safe for women & elder passengers.'
  },
  {
    id: 'route-102',
    driver_id: 'driver-2',
    driver_name: 'Sukhdev Singh',
    driver_phone: '+91 98234 11223',
    driver_rating: 4.8,
    vehicle_type: 'Tata Magic / Mini-Van',
    vehicle_model: 'Tata Magic Gold 7-Seater',
    plate_number: 'PB-10-CZ-8821',
    origin: 'Fatehgarh Rural Hub',
    destination: 'Railway Junction & City Center',
    intermediate_stops: ['Barauda Village Turn', 'Polytechnic College Gate', 'Highway Bypass', 'Station Platform 1'],
    departure_time: '08:45 AM',
    frequency: 'Every 2 Hours (8 AM to 7 PM)',
    price_per_seat: 35,
    available_seats: 3,
    total_seats: 7,
    luggage_space: 'Moderate bags, school satchels & parcels',
    has_carrier: true,
    is_ac: false,
    status: 'active',
    notes: 'Frequent shared rides. Direct drops at Railway station portico.'
  },
  {
    id: 'route-103',
    driver_id: 'driver-3',
    driver_name: 'Kailash Meena',
    driver_phone: '+91 99881 77263',
    driver_rating: 4.95,
    vehicle_type: 'Auto / E-Rickshaw',
    vehicle_model: 'Mahindra Treo Electric 4-Seater',
    plate_number: 'RJ-14-EA-2039',
    origin: 'Dharampura Gaon',
    destination: 'Block Tehsil & Supermarket',
    intermediate_stops: ['Primary Health Center', 'Panchayat Bhavan', 'Kalyanpur Mor'],
    departure_time: '09:15 AM',
    frequency: 'Continuous Shared Shuttle',
    price_per_seat: 20,
    available_seats: 2,
    total_seats: 4,
    luggage_space: 'Handbags and shopping baskets',
    has_carrier: false,
    is_ac: false,
    status: 'active',
    notes: 'Eco-friendly, smooth electric ride. Very affordable short-hop travel.'
  },
  {
    id: 'route-104',
    driver_id: 'driver-4',
    driver_name: 'Vikram Gurjar',
    driver_phone: '+91 97722 09182',
    driver_rating: 4.7,
    vehicle_type: 'Rural Express Bus',
    vehicle_model: 'Swaraj Mazda 24-Seater Rural Express',
    plate_number: 'HR-26-BK-7312',
    origin: 'Sonapur Tehsil',
    destination: 'State Capital Central Bus Stand',
    intermediate_stops: ['Khatoli Crossroad', 'Industrial Area Gate 3', 'Bypass Flyover', 'Metro Station'],
    departure_time: '06:30 AM',
    frequency: 'Twice Daily (6:30 AM & 2:00 PM)',
    price_per_seat: 75,
    available_seats: 12,
    total_seats: 24,
    luggage_space: 'Full boot + Underseat storage',
    has_carrier: true,
    is_ac: false,
    status: 'active',
    notes: 'Express route without unnecessary inner village detours. Fixed timing.'
  },
  {
    id: 'route-105',
    driver_id: 'driver-5',
    driver_name: 'Mohd. Aslam',
    driver_phone: '+91 98110 55432',
    driver_rating: 4.85,
    vehicle_type: 'Private Car / Shared Taxi',
    vehicle_model: 'Maruti Suzuki Ertiga (AC Shared)',
    plate_number: 'UP-32-DN-4401',
    origin: 'Chandpur Village',
    destination: 'Airport & Central Hub',
    intermediate_stops: ['Bithoor Cross', 'G.T. Road Toll', 'Civil Lines'],
    departure_time: '10:00 AM',
    frequency: 'Daily Scheduled',
    price_per_seat: 120,
    available_seats: 4,
    total_seats: 6,
    luggage_space: 'Spacious trunk + Comfortable AC seating',
    has_carrier: false,
    is_ac: true,
    status: 'active',
    notes: 'Air conditioned, fast & comfortable for long travel, airport visits and hospital trips.'
  }
];

export const POPULAR_LOCATIONS = [
  'Rampur Village Chowk',
  'District Main Mandi & Hospital',
  'Fatehgarh Rural Hub',
  'Railway Junction & City Center',
  'Dharampura Gaon',
  'Block Tehsil & Supermarket',
  'Sonapur Tehsil',
  'State Capital Central Bus Stand',
  'Chandpur Village',
  'Kisan Krishi Mandi',
  'Panchayat Bhavan',
  'Primary Health Center',
  'Industrial Area Gate 3'
];
