import { SharedRoute, UserProfile } from './types';

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'driver-erickshaw-1',
    email: 'kailash.toto@nextride.in',
    full_name: 'Kailash Meena',
    phone: '+91 99881 77263',
    role: 'driver',
    village_town: 'Rampur Village Chowk',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    rating: 4.95,
    total_trips: 420,
  },
  {
    id: 'driver-auto-2',
    email: 'ramesh.cng@nextride.in',
    full_name: 'Ramesh Patel',
    phone: '+91 98765 43210',
    role: 'driver',
    village_town: 'District Mandi Gate',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_trips: 680,
  },
  {
    id: 'traveller-1',
    email: 'anita.sharma@gmail.com',
    full_name: 'Anita Sharma',
    phone: '+91 97112 33445',
    role: 'traveller',
    village_town: 'Bhopalpur Sector 4',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    rating: 5.0,
    total_trips: 34,
  }
];

export const INITIAL_ROUTES: SharedRoute[] = [
  {
    id: 'route-e101',
    driver_id: 'driver-erickshaw-1',
    driver_name: 'Kailash Meena',
    driver_phone: '+91 99881 77263',
    driver_rating: 4.95,
    driver_experience: '4 yrs • 1,200+ Toto Rides',
    driver_avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    vehicle_type: 'E-Rickshaw Shared (Toto / Electric)',
    vehicle_model: 'Mahindra Treo Electric 4-Seater (Toto)',
    plate_number: 'DL-5E-AR-4091',
    origin: 'Rampur Village Chowk',
    destination: 'Krishi Mandi & Tehsil Hub',
    intermediate_stops: ['Panchayat Bhavan', 'Old Toll Naka', 'Primary Health Center', 'Sabzi Mandi Gate 2'],
    departure_time: 'Every 5 mins (Instant Shuttle)',
    frequency: 'Continuous Electric Shuttle (6 AM - 9 PM)',
    price_per_seat: 15,
    full_vehicle_price: 60,
    available_seats: 3,
    total_seats: 4,
    luggage_space: 'Handbags, shopping sacks & farm produce bags',
    has_carrier: false,
    is_electric: true,
    eta_mins: 3,
    distance_km: 4.2,
    status: 'active',
    current_location: { x: 28, y: 35, label: 'Near Panchayat Bhavan' },
    notes: 'Silent, smooth 100% electric ride. Dedicated front/rear grab handles for elders.'
  },
  {
    id: 'route-a202',
    driver_id: 'driver-auto-2',
    driver_name: 'Ramesh Patel',
    driver_phone: '+91 98765 43210',
    driver_rating: 4.88,
    driver_experience: '7 yrs • Top Rated Auto Partner',
    driver_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    vehicle_type: 'Shared CNG Auto (6-Seater)',
    vehicle_model: 'Bajaj Maxima Z CNG 6-Seater Auto',
    plate_number: 'UP-32-AT-8812',
    origin: 'Fatehgarh Rural Hub',
    destination: 'Railway Junction & City Center',
    intermediate_stops: ['Kalyanpur Mor', 'Polytechnic College Gate', 'Highway Bypass Flyover', 'Platform 1 Portico'],
    departure_time: 'Every 8 mins',
    frequency: 'Every 8-10 Mins (5 AM - 10:30 PM)',
    price_per_seat: 25,
    full_vehicle_price: 130,
    available_seats: 4,
    total_seats: 6,
    luggage_space: 'Heavy luggage carrier on top + underseat boot',
    has_carrier: true,
    is_electric: false,
    eta_mins: 5,
    distance_km: 7.8,
    status: 'active',
    current_location: { x: 55, y: 48, label: 'At Kalyanpur Mor' },
    notes: 'High-speed CNG auto connecting directly to Railway Station entrance.'
  },
  {
    id: 'route-e103',
    driver_id: 'driver-3',
    driver_name: 'Satish Kumar',
    driver_phone: '+91 98112 44331',
    driver_rating: 4.92,
    driver_experience: '3 yrs • Green Champion',
    driver_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    vehicle_type: 'E-Rickshaw Shared (Toto / Electric)',
    vehicle_model: 'Yatri EV High-Power E-Rickshaw',
    plate_number: 'RJ-14-EA-9923',
    origin: 'Dharampura Gaon',
    destination: 'Block Tehsil & Supermarket',
    intermediate_stops: ['Government High School', 'Civil Hospital Corner', 'Post Office Chowk'],
    departure_time: 'Departs in 4 mins',
    frequency: 'Continuous Loop',
    price_per_seat: 10,
    full_vehicle_price: 45,
    available_seats: 2,
    total_seats: 4,
    luggage_space: 'Shopping baskets & school satchels',
    has_carrier: false,
    is_electric: true,
    eta_mins: 4,
    distance_km: 2.9,
    status: 'active',
    current_location: { x: 72, y: 25, label: 'Near High School' },
    notes: 'Super economical ₹10 short-distance Toto ride.'
  },
  {
    id: 'route-p303',
    driver_id: 'driver-4',
    driver_name: 'Baldev Singh',
    driver_phone: '+91 97722 09182',
    driver_rating: 4.85,
    driver_experience: '5 yrs • Agri Express Specialist',
    driver_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    vehicle_type: 'Auto Parcel / Agri Cargo',
    vehicle_model: 'Piaggio Ape Cargo E-Auto / Delivery Loader',
    plate_number: 'PB-10-LC-7744',
    origin: 'Kisan Krishi Mandi',
    destination: 'Grain Market & Cold Storage',
    intermediate_stops: ['Warehouse No. 4', 'Wholesale Bazar', 'Highway Toll Checkpost'],
    departure_time: 'On-Demand Instant',
    frequency: 'Instant Cargo Dispatch',
    price_per_seat: 30,
    full_vehicle_price: 150,
    available_seats: 1,
    total_seats: 2,
    luggage_space: 'Full 500kg cargo deck for crates, sacks & cartons',
    has_carrier: true,
    is_electric: false,
    eta_mins: 8,
    distance_km: 9.5,
    status: 'active',
    current_location: { x: 42, y: 78, label: 'Loading at Mandi Gate' },
    notes: 'Ideal for sending vegetable crates, farm harvest, dairy cans and parcels.'
  },
  {
    id: 'route-a204',
    driver_id: 'driver-5',
    driver_name: 'Mohd. Imran',
    driver_phone: '+91 98221 00987',
    driver_rating: 4.9,
    driver_experience: '6 yrs • Super Fast Auto',
    driver_avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    vehicle_type: 'Full Auto (Private Booking)',
    vehicle_model: 'TVS King Deluxe Auto (Entire Vehicle)',
    plate_number: 'MP-09-RA-3321',
    origin: 'Sonapur Tehsil',
    destination: 'District Central Hospital',
    intermediate_stops: ['Direct Fast Non-Stop (Door to Door)'],
    departure_time: 'Instant Pickup',
    frequency: 'Private On-Demand',
    price_per_seat: 90,
    full_vehicle_price: 90,
    available_seats: 4,
    total_seats: 4,
    luggage_space: 'Full trunk + luggage carrier',
    has_carrier: true,
    is_electric: false,
    eta_mins: 2,
    distance_km: 6.4,
    status: 'active',
    current_location: { x: 80, y: 65, label: 'Standing at Sonapur Stand' },
    notes: 'Private full auto ride with zero co-passenger stops for urgent and family trips.'
  }
];

export const POPULAR_LOCATIONS = [
  'Rampur Village Chowk',
  'Krishi Mandi & Tehsil Hub',
  'Fatehgarh Rural Hub',
  'Railway Junction & City Center',
  'Dharampura Gaon',
  'Block Tehsil & Supermarket',
  'Sonapur Tehsil',
  'District Central Hospital',
  'Sabzi Mandi Gate 2',
  'Panchayat Bhavan',
  'Primary Health Center',
  'Polytechnic College Gate'
];
